### PR TITLE
WIP: fix getContentByService

### PR DESCRIPTION
**Pull request by amy-actually**
working on getContentBy Service errors: This fix resolved content load locally when installed merged/updated local version of feathers (issue 9, issue 35, & issue 36)

service-content-tawny

**ToDo**:
- [ ] Fix card links
- [ ] Increase threshold for fetching data?

### CODE REVIEW

**Comment by amy-actually** [comment]
resolved
~~Error in feathers:
`\[Vue warn]: Property or method "blog" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`~~

**Comment by amy-actually** [comment]
**WARNING**
`vendors.app.js:2067 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

**Review by michaelschofield — APPROVED** [review]
Looks good! APproving and merging.

**Comment by michaelschofield** [comment]
>  `vendors.app.js:2067 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.`

This is good to log. Deprecation means that in the next major version of MOmentJS this method isn't going to be included. So we will have to - then - transform the date value. For as long as we currently use this version of Moment, though, we're solid.

**Pull request merged**
